version: '3'

services:
  db:
    container_name: postgres.storage
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
    - 5433:5432