# Generated by Django 2.2.5 on 2020-09-28 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('json_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
